# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca41f9d5e5077824ab86e4dfdde77eeede39252b4938dbeec2db3ec4e881ccca54c871f0eebfb8f3f6a1bb11f339e047bbb3740a6858cc04d71976c2d034d2fa

test:
  secret_key_base: 821db9b406bbf2d8586c4ebfb3f361a17a0fb1eb5c976a395aa57dc6f0ff9a5d313c52538ab56e166f90c5d418b97627022d69305a0a458862649df0fd992bba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
